spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce-database
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

order-service:
  kafka:
    topics:
      order-created: order-created
      product-reservation: product-reservation
    group-id: ${spring.application.name}

server:
  port: 8081